version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8000"
    environment:
      - MONGODB_CONNECTION_STRING=mongodb+srv://impsuraj1996:tIKCktdcnKeTgN17@tinuurl.zhlw9.mongodb.net/?retryWrites=true&w=majority&appName=tinuurll
      - REDIS_HOST=red-cu8kgh9opnds73d74ko0
      - REDIS_PORT=6379
      - PORT=8000
      - APP_SECRET=MYSELFSURAJ
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
